# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

status is-login; and begin

    # Login shell initialisation


end

status is-interactive; and begin

    # Abbreviations


    # Aliases
    alias ga 'git add'
    alias gc 'git commit'
    alias gco 'git checkout'
    alias gcp 'git cherry-pick'
    alias gdiff 'git diff'
    alias gl 'git prettylog'
    alias gp 'git push'
    alias gs 'git status'
    alias gt 'git tag'
    alias jf 'jj git fetch'
    alias jn 'jj new'
    alias js 'jj st'
    alias pbcopy xclip
    alias pbpaste 'xclip -o'

    # Interactive shell initialisation
    set -gx GPG_TTY (tty)


    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/adalton/.local/share/fish/home-manager_generated_completions" $post
    end

    source /nix/store/bn225jc9h5n0z5fni59iv77fiqj2ldwz-source/functions/fish_prompt.fish
    source /nix/store/bn225jc9h5n0z5fni59iv77fiqj2ldwz-source/functions/fish_right_prompt.fish
    source /nix/store/bn225jc9h5n0z5fni59iv77fiqj2ldwz-source/functions/fish_title.fish
    #-------------------------------------------------------------------------------
    # SSH Agent
    #-------------------------------------------------------------------------------
    function __ssh_agent_is_started -d "check if ssh agent is already started"
        if begin
                test -f $SSH_ENV; and test -z "$SSH_AGENT_PID"
            end
            source $SSH_ENV >/dev/null
        end

        if test -z "$SSH_AGENT_PID"
            return 1
        end

        ssh-add -l >/dev/null 2>&1
        if test $status -eq 2
            return 1
        end
    end

    function __ssh_agent_start -d "start a new ssh agent"
        ssh-agent -c | sed 's/^echo/#echo/' >$SSH_ENV
        chmod 600 $SSH_ENV
        source $SSH_ENV >/dev/null
        ssh-add
    end

    if not test -d $HOME/.ssh
        mkdir -p $HOME/.ssh
        chmod 0700 $HOME/.ssh
    end

    if test -d $HOME/.gnupg
        chmod 0700 $HOME/.gnupg
    end

    if test -z "$SSH_ENV"
        set -xg SSH_ENV $HOME/.ssh/environment
    end

    if not __ssh_agent_is_started
        __ssh_agent_start
    end


    # Add ~/.local/bin
    set -q PATH; or set PATH ''
    set -gx PATH "$HOME/.local/bin" $PATH

    #-------------------------------------------------------------------------------
    # Prompt
    #-------------------------------------------------------------------------------
    # Do not show any greeting
    set --universal --erase fish_greeting
    function fish_greeting
    end
    funcsave fish_greeting

    # bobthefish theme
    set -g theme_color_scheme dracula

    # My color scheme
    set -U fish_color_normal normal
    set -U fish_color_command F8F8F2
    set -U fish_color_quote F1FA8C
    set -U fish_color_redirection 8BE9FD
    set -U fish_color_end 50FA7B
    set -U fish_color_error FF5555
    set -U fish_color_param 5FFFFF
    set -U fish_color_comment 6272A4
    set -U fish_color_match --background=brblue
    set -U fish_color_selection white --bold --background=brblack
    set -U fish_color_search_match bryellow --background=brblack
    set -U fish_color_history_current --bold
    set -U fish_color_operator 00a6b2
    set -U fish_color_escape 00a6b2
    set -U fish_color_cwd green
    set -U fish_color_cwd_root red
    set -U fish_color_valid_path --underline
    set -U fish_color_autosuggestion BD93F9
    set -U fish_color_user brgreen
    set -U fish_color_host normal
    set -U fish_color_cancel -r
    set -U fish_pager_color_completion normal
    set -U fish_pager_color_description B3A06D yellow
    set -U fish_pager_color_prefix white --bold --underline
    set -U fish_pager_color_progress brwhite --background=cyan

    # Override the nix prompt for the theme so that we show a more concise prompt
    function __bobthefish_prompt_nix -S -d 'Display current nix environment'
        [ "$theme_display_nix" = no -o -z "$IN_NIX_SHELL" ]
        and return

        __bobthefish_start_segment $color_nix
        echo -ns N ' '

        set_color normal
    end

    #-------------------------------------------------------------------------------
    # Vars
    #-------------------------------------------------------------------------------
    # Modify our path to include our Go binaries
    contains $HOME/code/go/bin $fish_user_paths; or set -Ua fish_user_paths $HOME/code/go/bin
    contains $HOME/bin $fish_user_paths; or set -Ua fish_user_paths $HOME/bin

    # Exported variables
    if isatty
        set -x GPG_TTY (tty)
    end

    # Editor
    set -gx EDITOR micro
    
    #-------------------------------------------------------------------------------
    # Functions
    #-------------------------------------------------------------------------------
    # Shortcut to setup a nix-shell with fish. This lets you do something like
    # `fnix -p go` to get an environment with Go but use the fish shell along
    # with it.
    alias fnix "nix-shell --run fish"

    set -g SHELL /nix/store/28sw33ddggf3mmmglxqrxrqikwbfsk5j-fish-4.0.2/bin/fish 
    /nix/store/bqkp6cxz0lp3033iixxm2kvykvfsqvf8-direnv-2.37.1/bin/direnv hook fish | source


end
